services:
  redis:
    image: redis:7
    container_name: redis
    mem_limit: 512m 
    ports:
      - "6379:6379"
    restart: unless-stopped
  laravel:
    build:
      context: ./laravel_jets_cobelmon_admin
      dockerfile: docker/Dockerfile
    container_name: laravel
    ports:
      - "8000:8000"
    volumes:
      - ./laravel_jets_cobelmon_admin:/var/www/html
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: laravel
      DB_PASSWORD: secret
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - db
      - redis
    command: php artisan serve --host=0.0.0.0 --port=8000
  db:
    image: mysql:8
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped
  minecraft:
    image: itzg/minecraft-server
    container_name: minecraft
    ports:
      - "25565:25565"
    environment:
      TYPE: "FABRIC"
      VERSION: "1.21.1"
      FABRIC_LOADER_VERSION: "0.16.14"
      EULA: "TRUE"
      MEMORY: 6G
    volumes:
      - ./minecraf_cobelmon_server:/data
    tty: true
    stdin_open: true
    restart: unless-stopped

volumes:
  db_data:
